/**
 * NUR Lingo — Ընդlayнvats Bararan v2
 * 100+ entries: Yntaniq, Kencaghayin, Amenorya, Shrjapat, Usucum, Erkir
 */
export type GrammarType = "noun"|"verb"|"adjective"|"adverb"|"pronoun"|"preposition"|"conjunction"|"interjection"|"numeral"|"particle";
export type SemanticCategory = "home_living"|"food_drink"|"family_relationships"|"travel_movement"|"emotions_feelings"|"time_calendar"|"colors_appearance"|"nature_environment"|"work_profession"|"education_learning"|"health_body"|"numbers_math"|"greetings_politeness"|"verbs_motion"|"verbs_communication"|"verbs_cognition"|"pronouns_core"|"adjectives_basic"|"clothing"|"weather"|"animals"|"city_transport"|"daily_routine"|"shopping"|"hobbies"|"technology";
export interface ExampleSentence { armenian:string; english:string; level:1|2|3; acceptable_variants?:string[]; }
export interface LexiconEntry { id:string; word:string; english:string[]; synonyms:string[]; antonyms?:string[]; grammar_type:GrammarType; difficulty:1|2|3|4|5; examples:ExampleSentence[]; embedding_group:SemanticCategory; lesson_tags:string[]; related_forms?:string[]; notes?:string; frequency_rank?:number; gender_note?:string; }
export interface SentencePattern { id:string; english_template:string; armenian_variants:string[]; grammar_note?:string; difficulty:1|2|3|4|5; lesson_tags:string[]; semantic_group:string; }

export const LEXICON: LexiconEntry[] = [
  // PRONOUNS
  {id:"pron_001",word:"ես",english:["I","me"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:1,examples:[{armenian:"Ես հայ եմ",english:"I am Armenian",level:1,acceptable_variants:["Հայ եմ"]}]},
  {id:"pron_002",word:"դու",english:["you (singular)"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:3,examples:[{armenian:"Դու լավ ես",english:"You are fine",level:1}]},
  {id:"pron_003",word:"նա",english:["he","she","it"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:5,notes:"No gender in Armenian 3rd person",examples:[{armenian:"Նա գնում է",english:"He/She is going",level:1}]},
  {id:"pron_004",word:"մենք",english:["we"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:8,examples:[{armenian:"Մենք հայ ենք",english:"We are Armenian",level:1}]},
  {id:"pron_005",word:"դուք",english:["you (plural/formal)"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:10,examples:[{armenian:"Դուք հայ եք",english:"You are Armenian (pl.)",level:1}]},
  {id:"pron_006",word:"նրանք",english:["they"],synonyms:[],grammar_type:"pronoun",difficulty:1,embedding_group:"pronouns_core",lesson_tags:["lesson_1"],frequency_rank:9,examples:[{armenian:"Նրանք Երևանում են",english:"They are in Yerevan",level:1}]},
  // FAMILY
  {id:"fam_001",word:"մայր",english:["mother"],synonyms:["մամա","մայրիկ"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:18,related_forms:["մոր","մայրս","մայրիկս"],notes:"մայрс = my mother (natural suffix form)",examples:[{armenian:"Մայրս բժշկուhի է",english:"My mother is a doctor",level:1,acceptable_variants:["Իmy mायры bjishk e","Мayrikms bjshkuhi e","Mayrs bjishk e"]}]},
  {id:"fam_002",word:"հayр",english:["father"],synonyms:["բаба","hаyрик"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:19,related_forms:["hoр","hаyрс","hаyрикис"],notes:"հаyрс = my father (suffix, natural)",examples:[{armenian:"Hаyрс ususich e",english:"My father is a teacher",level:1,acceptable_variants:["Im hаyрy ususich e"]}]},
  {id:"fam_003",word:"маyрик",english:["mom","mommy"],synonyms:["маyр","маma"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:22,related_forms:["маyрикис","маyрикс"],examples:[{armenian:"Мayriks shat lav e",english:"My mom is very kind",level:1}]},
  {id:"fam_004",word:"hаyрик",english:["dad","daddy"],synonyms:["hаyр","баba"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:23,related_forms:["hаyрикс"],examples:[{armenian:"Hаyriks tun yekav",english:"My dad came home",level:1}]},
  {id:"fam_005",word:"quyр",english:["sister"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:30,related_forms:["qroj","quyрс"],examples:[{armenian:"Quyрs usanox e",english:"My sister is a student",level:1}]},
  {id:"fam_006",word:"yeğbayr",english:["brother"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:31,related_forms:["yeğborс"],examples:[{armenian:"Yeğbayрs Erevanum e",english:"My brother is in Yerevan",level:1}]},
  {id:"fam_007",word:"papik",english:["grandfather","grandpa"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:35,examples:[{armenian:"Papiks 70 taregan e",english:"My grandfather is 70 years old",level:2}]},
  {id:"fam_008",word:"tatik",english:["grandmother","grandma"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:36,examples:[{armenian:"Tatiks hac e thxum",english:"My grandma is baking bread",level:2}]},
  {id:"fam_009",word:"yerxan",english:["child","kid"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:28,examples:[{armenian:"Yerxany pokr e",english:"The child is small",level:1}]},
  {id:"fam_010",word:"ënker",english:["friend"],synonyms:["barékam"],grammar_type:"noun",difficulty:1,embedding_group:"family_relationships",lesson_tags:["lesson_4"],frequency_rank:22,related_forms:["ënkeruoj","ënkeрs"],examples:[{armenian:"Ënkers lav mard e",english:"My friend is a good person",level:1,acceptable_variants:["Im ënkery lav mard e"]}]},
  {id:"fam_011",word:"amushnak",english:["husband"],synonyms:[],grammar_type:"noun",difficulty:2,embedding_group:"family_relationships",lesson_tags:["lesson_6"],frequency_rank:45,examples:[{armenian:"Amushнаks Erevanum e ashxatum",english:"My husband works in Yerevan",level:2}]},
  {id:"fam_012",word:"kushakits",english:["wife"],synonyms:[],grammar_type:"noun",difficulty:2,embedding_group:"family_relationships",lesson_tags:["lesson_6"],frequency_rank:46,examples:[{armenian:"Kushakitss nkaraguych e",english:"My wife is an artist",level:2}]},
  // HOME
  {id:"home_001",word:"tun",english:["home","house"],synonyms:["bnakaran"],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:12,related_forms:["tan","tnits","tner"],examples:[{armenian:"Ës gnum em tun",english:"I am going home",level:1,acceptable_variants:["Ës tun em gnum","Tun em gnum"]}]},
  {id:"home_002",word:"senyak",english:["room","bedroom"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:38,related_forms:["senyaki","senyakum"],examples:[{armenian:"Im senyakum em",english:"I am in my room",level:1}]},
  {id:"home_003",word:"banavor",english:["kitchen"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:42,examples:[{armenian:"Mayrs bnavorum e",english:"My mom is in the kitchen",level:1}]},
  {id:"home_004",word:"dur",english:["door"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:33,examples:[{armenian:"Dury bats e",english:"The door is open",level:1}]},
  {id:"home_005",word:"patuhan",english:["window"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:37,examples:[{armenian:"Patuhany pak e",english:"The window is closed",level:1}]},
  {id:"home_006",word:"shart",english:["bed"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:40,examples:[{armenian:"Ës koshum em shartim",english:"I am sleeping in bed",level:1}]},
  {id:"home_007",word:"sezhan",english:["table","desk"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:36,examples:[{armenian:"Girqy sezhanin e",english:"The book is on the table",level:1}]},
  {id:"home_008",word:"ambion",english:["chair"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:39,examples:[{armenian:"Nstir ambionin",english:"Sit on the chair",level:1}]},
  {id:"home_009",word:"jermak",english:["TV","television"],synonyms:["televizor"],grammar_type:"noun",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:30,examples:[{armenian:"Jermak enq nayum",english:"We are watching TV",level:1}]},
  // FOOD
  {id:"food_001",word:"jur",english:["water"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:15,related_forms:["jri","jrits"],examples:[{armenian:"Ës jur em xnum",english:"I am drinking water",level:1}]},
  {id:"food_002",word:"hac",english:["bread","food"],synonyms:["kerakur"],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:20,examples:[{armenian:"Ës hac em utum",english:"I am eating bread",level:1}]},
  {id:"food_003",word:"kath",english:["milk"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:32,examples:[{armenian:"Yerxany kath e xnum",english:"The child is drinking milk",level:1}]},
  {id:"food_004",word:"dzukh",english:["egg","eggs"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:35,examples:[{armenian:"Arbanyan dzukhner enq utum",english:"We eat eggs in the morning",level:1}]},
  {id:"food_005",word:"mis",english:["meat"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:38,examples:[{armenian:"Khorovatsы mis e",english:"Khorovats is meat",level:1}]},
  {id:"food_006",word:"matsun",english:["yogurt (Armenian matzoon)"],synonyms:["ban"],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:40,notes:"Traditional Armenian yogurt — cultural staple",examples:[{armenian:"Matsune hamov e",english:"Matsun is tasty",level:1}]},
  {id:"food_007",word:"mrghabar",english:["fruit"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:36,examples:[{armenian:"Ës mrghabar em sirum",english:"I love fruit",level:1}]},
  {id:"food_008",word:"banshabar",english:["vegetable"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:37,examples:[{armenian:"Banshabarneгy jansaghov en",english:"Vegetables are healthy",level:1}]},
  {id:"food_009",word:"surj",english:["coffee"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:25,notes:"Armenian coffee culture is central to daily life",examples:[{armenian:"Ës hayкakan surj em xnum",english:"I drink Armenian coffee",level:1}]},
  {id:"food_010",word:"te",english:["tea"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:26,examples:[{armenian:"Ës te em xnum",english:"I am drinking tea",level:1}]},
  {id:"food_011",word:"hamov",english:["tasty","delicious"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:30,examples:[{armenian:"Khorovatsы shat hamov e",english:"Khorovats is very tasty",level:1}]},
  {id:"food_012",word:"noр",english:["pomegranate"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:44,notes:"NUR Lingo mascot named after pomegranate — Armenia's national symbol",examples:[{armenian:"Nory Hayastani xorkhrdn e",english:"The pomegranate is Armenia's symbol",level:2}]},
  {id:"food_013",word:"dziran",english:["apricot"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:45,notes:"Armenia is historically the birthplace of the apricot (Prunus armeniaca)",examples:[{armenian:"Hayastany dziranov hasheshvats e",english:"Armenia is famous for apricots",level:2}]},
  // DAILY ROUTINE
  {id:"daily_001",word:"arbanyan",english:["morning"],synonyms:["aravarot"],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:20,examples:[{armenian:"Bari arbanyan",english:"Good morning",level:1,acceptable_variants:["Bari loys"]}]},
  {id:"daily_002",word:"keson",english:["afternoon","noon"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:25,examples:[{armenian:"Bari keson",english:"Good afternoon",level:1}]},
  {id:"daily_003",word:"erkuy",english:["evening"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:22,examples:[{armenian:"Bari erkuy",english:"Good evening",level:1}]},
  {id:"daily_004",word:"gisher",english:["night"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:23,examples:[{armenian:"Bari gisher",english:"Good night",level:1}]},
  {id:"daily_005",word:"or",english:["day"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:14,related_forms:["ori","orvits","orer"],examples:[{armenian:"Aysor lav or e",english:"Today is a good day",level:1}]},
  {id:"daily_006",word:"aysor",english:["today"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:13,examples:[{armenian:"Aysor areg ka",english:"There is sun today",level:1}]},
  {id:"daily_007",word:"verakandz",english:["tomorrow"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:16,examples:[{armenian:"Verakandz dproс em gnum",english:"Tomorrow I go to school",level:1}]},
  {id:"daily_008",word:"yerek",english:["yesterday"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:17,examples:[{armenian:"Yerek tun menitsi",english:"Yesterday I stayed home",level:1}]},
  {id:"daily_009",word:"zartnl",english:["to wake up"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:35,related_forms:["zartnum em","zartnetsi"],examples:[{armenian:"Ës vagh em zartnm",english:"I wake up early",level:1}]},
  {id:"daily_010",word:"koshnel",english:["to sleep"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:33,related_forms:["koshum em","koshets em"],examples:[{armenian:"Ës karots em koshum",english:"I want to sleep",level:1}]},
  {id:"daily_011",word:"lvanal",english:["to wash","to bathe"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"daily_routine",lesson_tags:["lesson_6"],frequency_rank:40,related_forms:["lvanum em"],examples:[{armenian:"Arbanyan lvanum em",english:"I wash in the morning",level:1}]},
  {id:"daily_012",word:"ashxatel",english:["to work"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"work_profession",lesson_tags:["lesson_7"],frequency_rank:14,related_forms:["ashxatum em","ashxatetsem"],examples:[{armenian:"Ës ashxatum em Erevanum",english:"I work in Yerevan",level:1}]},
  // CORE VERBS
  {id:"verb_001",word:"gnal",english:["to go","to leave"],synonyms:["meknel"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_motion",lesson_tags:["lesson_2"],frequency_rank:7,related_forms:["gnum em","gnum es","gnum e","gnatsi","gnats","kgnam"],examples:[{armenian:"Ës gnum em tun",english:"I am going home",level:1,acceptable_variants:["Ës tun em gnum","Tun em gnum"]}]},
  {id:"verb_002",word:"gal",english:["to come"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_motion",lesson_tags:["lesson_2"],frequency_rank:9,related_forms:["galis em","yeka","yekav","kgam"],examples:[{armenian:"Ës galis em",english:"I am coming",level:1}]},
  {id:"verb_003",word:"linel",english:["to be","to exist","to become"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_1"],frequency_rank:2,related_forms:["em","es","e","enq","eq","en","ei","er","yeğa","yeğav","klilem"],examples:[{armenian:"Ës usanox em",english:"I am a student",level:1},{armenian:"Mayrs bjshkuhi e",english:"My mother is a doctor",level:1}]},
  {id:"verb_004",word:"utel",english:["to eat"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:28,related_forms:["utum em","utum es","utum e","kera","kerav"],examples:[{armenian:"Ës hac em utum",english:"I am eating bread",level:1,acceptable_variants:["Ës utum em hac","Hac em utum"]}]},
  {id:"verb_005",word:"xmel",english:["to drink"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"food_drink",lesson_tags:["lesson_3"],frequency_rank:29,related_forms:["xnum em","xnum e","xmetsem"],examples:[{armenian:"Ës surj em xnum",english:"I am drinking coffee",level:1}]},
  {id:"verb_006",word:"xosel",english:["to speak","to talk"],synonyms:["asel"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_communication",lesson_tags:["lesson_2"],frequency_rank:20,related_forms:["xosum em","xosum es","xosum e","xosetsi"],examples:[{armenian:"Ës hayeren em xosum",english:"I speak Armenian",level:1}]},
  {id:"verb_007",word:"sirel",english:["to love","to like"],synonyms:["havanel"],grammar_type:"verb",difficulty:1,embedding_group:"emotions_feelings",lesson_tags:["lesson_4"],frequency_rank:16,related_forms:["sirum em","sirum es","sirum e","siretsi"],examples:[{armenian:"Ës sirum em Hayastany",english:"I love Armenia",level:1,acceptable_variants:["Hayastany sirum em"]}]},
  {id:"verb_008",word:"kardaltel",english:["to read"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:35,related_forms:["kardalum em","kardalum es","kardatsi"],examples:[{armenian:"Ës gark em kardalum",english:"I am reading a book",level:1,acceptable_variants:["Ës kardalum em gark","Gark em kardalum"]}]},
  {id:"verb_009",word:"grel",english:["to write"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:32,related_forms:["grum em","grum es","gretsi"],examples:[{armenian:"Ës namar em grum",english:"I am writing a letter",level:1}]},
  {id:"verb_010",word:"uzel",english:["to want","to wish"],synonyms:["tsankanalel"],grammar_type:"verb",difficulty:1,embedding_group:"emotions_feelings",lesson_tags:["lesson_3"],frequency_rank:13,related_forms:["uzum em","uzum es","uzetsi"],examples:[{armenian:"Ës uzum em jur",english:"I want water",level:1,acceptable_variants:["Jur em uzum"]}]},
  {id:"verb_011",word:"aprel",english:["to live","to reside"],synonyms:["bnakvl"],grammar_type:"verb",difficulty:1,embedding_group:"home_living",lesson_tags:["lesson_2"],frequency_rank:21,related_forms:["aprum em","aprum es","aprum e","apretsi"],examples:[{armenian:"Ës Erevanum em aprum",english:"I live in Yerevan",level:1,acceptable_variants:["Ës aprum em Erevanum","Erevanum em aprum"]}]},
  {id:"verb_012",word:"haskanal",english:["to understand"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_1"],frequency_rank:15,related_forms:["haskanum em","haskanum es","haskatsi"],examples:[{armenian:"Ës haskanum em",english:"I understand",level:1,acceptable_variants:["Haskanum em"]}]},
  {id:"verb_013",word:"soverel",english:["to learn","to study"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:20,related_forms:["soverum em","soverum es","sovoretsi"],examples:[{armenian:"Ës hayeren em soverum",english:"I am learning Armenian",level:1}]},
  {id:"verb_014",word:"tel",english:["to give"],synonyms:[],grammar_type:"verb",difficulty:1,embedding_group:"verbs_communication",lesson_tags:["lesson_5"],frequency_rank:18,related_forms:["talis em","talis es","etsi","etav"],examples:[{armenian:"Ints jur tal?",english:"Can you give me water?",level:2}]},
  {id:"verb_015",word:"tesnl",english:["to see","to look","to watch"],synonyms:["nayel"],grammar_type:"verb",difficulty:1,embedding_group:"verbs_cognition",lesson_tags:["lesson_2"],frequency_rank:17,related_forms:["tesnum em","tesnum es","tesaw","ktenam"],examples:[{armenian:"Ës jermak em tesnum",english:"I am watching TV",level:1}]},
  // CITY & ENVIRONMENT
  {id:"city_001",word:"Hayastan",english:["Armenia"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_1"],frequency_rank:10,related_forms:["Hayastani","Hayastanits","Hayastanum"],examples:[{armenian:"Ës sirum em Hayastany",english:"I love Armenia",level:1}]},
  {id:"city_002",word:"Erevan",english:["Yerevan"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_1"],frequency_rank:11,related_forms:["Erevani","Erevanits","Erevanum"],examples:[{armenian:"Ës aprum em Erevanum",english:"I live in Yerevan",level:1}]},
  {id:"city_003",word:"purac",english:["street","road"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:28,examples:[{armenian:"Puraky mets e",english:"The street is big",level:1}]},
  {id:"city_004",word:"xanut",english:["store","shop"],synonyms:["shopon"],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:30,examples:[{armenian:"Xanut em gnum",english:"I am going to the store",level:1}]},
  {id:"city_005",word:"bajin",english:["price"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:35,examples:[{armenian:"Inch bajin e?",english:"What is the price?",level:1}]},
  {id:"city_006",word:"shuk",english:["market","bazaar"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"shopping",lesson_tags:["lesson_7"],frequency_rank:32,examples:[{armenian:"Shuk em gnum",english:"I am going to the market",level:1}]},
  {id:"city_007",word:"avetobus",english:["bus"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:33,examples:[{armenian:"Avetobusom em nasum",english:"I am riding the bus",level:1}]},
  {id:"city_008",word:"metro",english:["subway","metro"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"city_transport",lesson_tags:["lesson_7"],frequency_rank:36,examples:[{armenian:"Erevany metro uni",english:"Yerevan has a metro",level:1}]},
  {id:"city_009",word:"park",english:["park"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_7"],frequency_rank:38,examples:[{armenian:"Park enq gnum",english:"We are going to the park",level:1}]},
  // NATURE
  {id:"nat_001",word:"areg",english:["sun"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:28,examples:[{armenian:"Aregy paylatum e",english:"The sun is shining",level:1}]},
  {id:"nat_002",word:"andzrev",english:["rain"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"weather",lesson_tags:["lesson_8"],frequency_rank:30,examples:[{armenian:"Andzrev e galis",english:"It is raining",level:1}]},
  {id:"nat_003",word:"tsov",english:["lake","sea"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:35,notes:"Sevan is the famous Armenian lake",examples:[{armenian:"Sevan tsovy gshetsik e",english:"Lake Sevan is beautiful",level:1}]},
  {id:"nat_004",word:"ler",english:["mountain"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:32,notes:"Aragats and Ararat are iconic Armenian mountains",examples:[{armenian:"Ararat lery shat mets e",english:"Mount Ararat is very big",level:1}]},
  {id:"nat_005",word:"dzar",english:["tree"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:38,examples:[{armenian:"Dzary mets e",english:"The tree is big",level:1}]},
  {id:"nat_006",word:"dzaghik",english:["flower"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:40,examples:[{armenian:"Dzaghiky gshetsik e",english:"The flower is beautiful",level:1}]},
  {id:"nat_007",word:"yerkink",english:["sky"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"nature_environment",lesson_tags:["lesson_8"],frequency_rank:33,examples:[{armenian:"Yerkinkы kapuyt e",english:"The sky is blue",level:1}]},
  {id:"nat_008",word:"dzayn",english:["snow"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"weather",lesson_tags:["lesson_8"],frequency_rank:42,examples:[{armenian:"Dzyуny spitat e",english:"The snow is white",level:1}]},
  // COLORS
  {id:"col_001",word:"karmir",english:["red"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:30,notes:"Armenian flag — top stripe",examples:[{armenian:"Karmir dzaghikы gshetsik e",english:"The red flower is beautiful",level:1}]},
  {id:"col_002",word:"kapuyt",english:["blue"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:31,notes:"Armenian flag — middle stripe",examples:[{armenian:"Yerkinkы kapuyt e",english:"The sky is blue",level:1}]},
  {id:"col_003",word:"narinjaguyn",english:["orange","apricot color"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:35,notes:"Armenian flag — bottom stripe",examples:[{armenian:"Dzirany narinjaguyn e",english:"The apricot is orange",level:1}]},
  {id:"col_004",word:"spitak",english:["white"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:32,examples:[{armenian:"Dzyuny spitak e",english:"The snow is white",level:1}]},
  {id:"col_005",word:"sev",english:["black"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:33,examples:[{armenian:"Gisheгy sev e",english:"The night is black",level:1}]},
  {id:"col_006",word:"kanataguyn",english:["green"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:36,examples:[{armenian:"Kary kanataguyn e",english:"The grass is green",level:1}]},
  {id:"col_007",word:"deshnaguyn",english:["yellow"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"colors_appearance",lesson_tags:["lesson_9"],frequency_rank:37,examples:[{armenian:"Aregy deshnaguyn e",english:"The sun is yellow",level:1}]},
  // NUMBERS
  {id:"num_001",word:"mek",english:["one","1"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:20,examples:[{armenian:"Mek hac",english:"One bread",level:1}]},
  {id:"num_002",word:"yerkus",english:["two","2"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:21,examples:[{armenian:"Yerkus dzukh",english:"Two eggs",level:1}]},
  {id:"num_003",word:"yerek",english:["three","3"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:22,examples:[{armenian:"Yerek dzar",english:"Three trees",level:1}]},
  {id:"num_004",word:"chors",english:["four","4"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:23,examples:[{armenian:"Chors ambion",english:"Four chairs",level:1}]},
  {id:"num_005",word:"hing",english:["five","5"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:24,examples:[{armenian:"Hing or",english:"Five days",level:1}]},
  {id:"num_006",word:"vets",english:["six","6"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:25,examples:[{armenian:"Vets jam",english:"Six o'clock",level:1}]},
  {id:"num_007",word:"yot",english:["seven","7"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:26,examples:[{armenian:"Shabathy yot or uni",english:"A week has seven days",level:1}]},
  {id:"num_008",word:"ut",english:["eight","8"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:27,examples:[{armenian:"Ut jam e",english:"It is eight o'clock",level:1}]},
  {id:"num_009",word:"inn",english:["nine","9"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:28,examples:[{armenian:"Inn amis",english:"Nine months",level:1}]},
  {id:"num_010",word:"tas",english:["ten","10"],synonyms:[],grammar_type:"numeral",difficulty:1,embedding_group:"numbers_math",lesson_tags:["lesson_9"],frequency_rank:29,examples:[{armenian:"Tas HAYQ",english:"Ten HAYQ",level:1}]},
  // GREETINGS
  {id:"greet_001",word:"barev",english:["hello","hi","bye (informal)"],synonyms:["voghjuyn"],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:4,examples:[{armenian:"Barev, inch e ka?",english:"Hello, what's up?",level:1}]},
  {id:"greet_002",word:"voghjuyn",english:["greetings","hello (formal)"],synonyms:["barev"],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:14,examples:[{armenian:"Voghjuyn, barev dzez",english:"Greetings to you",level:1}]},
  {id:"greet_003",word:"shnorhakalut'yun",english:["thank you","thanks"],synonyms:[],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:16,examples:[{armenian:"Shnorhakalut'yun, shat lav e",english:"Thank you, very good",level:1}]},
  {id:"greet_004",word:"neroghut'yun",english:["sorry","excuse me"],synonyms:[],grammar_type:"interjection",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:20,examples:[{armenian:"Neroghut'yun, chhaskatsi",english:"Sorry, I didn't understand",level:1}]},
  {id:"greet_005",word:"ayo",english:["yes"],synonyms:[],grammar_type:"particle",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:5,examples:[{armenian:"Ayo, haskatsem",english:"Yes, I understood",level:1}]},
  {id:"greet_006",word:"voch",english:["no"],synonyms:[],grammar_type:"particle",difficulty:1,embedding_group:"greetings_politeness",lesson_tags:["lesson_1"],frequency_rank:6,examples:[{armenian:"Voch, ch'em haskanum",english:"No, I don't understand",level:1}]},
  // ADJECTIVES
  {id:"adj_001",word:"mets",english:["big","large","great","old"],synonyms:["khoshor"],antonyms:["pokr"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:11,examples:[{armenian:"Tuny mets e",english:"The house is big",level:1}]},
  {id:"adj_002",word:"pokr",english:["small","little","young"],synonyms:[],antonyms:["mets"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:17,examples:[{armenian:"Yerxany pokr e",english:"The child is small",level:1}]},
  {id:"adj_003",word:"lav",english:["good","well","fine"],synonyms:["bari","hianali"],antonyms:["vat"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_1"],frequency_rank:6,examples:[{armenian:"Shat lav e",english:"Very good",level:1}]},
  {id:"adj_004",word:"vat",english:["bad","poor","wrong"],synonyms:[],antonyms:["lav"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:19,examples:[{armenian:"Vat e",english:"It is bad",level:1}]},
  {id:"adj_005",word:"nor",english:["new"],synonyms:[],antonyms:["hin"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:23,examples:[{armenian:"Sa nor gark e",english:"This is a new book",level:1}]},
  {id:"adj_006",word:"hin",english:["old","ancient"],synonyms:[],antonyms:["nor"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:24,examples:[{armenian:"Hin kaghaky gshetsik e",english:"The old city is beautiful",level:2}]},
  {id:"adj_007",word:"shat",english:["very","much","many","a lot"],synonyms:[],grammar_type:"adverb",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_1"],frequency_rank:7,examples:[{armenian:"Shat sirum em",english:"I love very much",level:1}]},
  {id:"adj_008",word:"gshetsik",english:["beautiful","gorgeous","lovely"],synonyms:["grchkunak"],grammar_type:"adjective",difficulty:1,embedding_group:"adjectives_basic",lesson_tags:["lesson_2"],frequency_rank:22,examples:[{armenian:"Hayastany gshetsik e",english:"Armenia is beautiful",level:1}]},
  {id:"adj_009",word:"jansaghov",english:["healthy"],synonyms:[],grammar_type:"adjective",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_5"],frequency_rank:35,examples:[{armenian:"Dzuxy jansaghov e",english:"The fish is healthy",level:1}]},
  // EDUCATION
  {id:"edu_001",word:"dproс",english:["school"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:25,related_forms:["dprocum","dprocits"],examples:[{armenian:"Ës dproс em gnum",english:"I am going to school",level:1,acceptable_variants:["Dpros em gnum"]}]},
  {id:"edu_002",word:"gark",english:["book"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:30,related_forms:["garki","garkits","garkov","garkum","garker"],examples:[{armenian:"Ës gark em kardalum",english:"I am reading a book",level:1}]},
  {id:"edu_003",word:"usanox",english:["student (university)"],synonyms:["ashakert"],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:28,examples:[{armenian:"Ës usanox em",english:"I am a student",level:1}]},
  {id:"edu_004",word:"ashakert",english:["student (school)","pupil"],synonyms:["usanox"],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:29,examples:[{armenian:"Ashakertneгy lav en soverum",english:"The students are learning well",level:1}]},
  // PROFESSIONS
  {id:"prof_001",word:"bjishk",english:["doctor (male/general)"],synonyms:["doktor"],grammar_type:"noun",difficulty:2,embedding_group:"work_profession",lesson_tags:["lesson_8"],frequency_rank:45,gender_note:"masculine/general",examples:[{armenian:"Bjishky yekav",english:"The doctor came",level:1}]},
  {id:"prof_002",word:"bjshkuhi",english:["female doctor"],synonyms:["bjishk"],grammar_type:"noun",difficulty:2,embedding_group:"work_profession",lesson_tags:["lesson_8"],frequency_rank:46,gender_note:"feminine",notes:"More natural when referring to female doctor",examples:[{armenian:"Mayrs bjshkuhi e",english:"My mother is a doctor",level:1,acceptable_variants:["Mayrs bjishk e","Im mayry bjshkuhi e"]}]},
  {id:"prof_003",word:"usucich",english:["teacher (male/general)"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:35,gender_note:"masculine/general",examples:[{armenian:"Hayrs usucich e",english:"My father is a teacher",level:1}]},
  {id:"prof_004",word:"usucuchi",english:["female teacher"],synonyms:["usucich"],grammar_type:"noun",difficulty:2,embedding_group:"education_learning",lesson_tags:["lesson_5"],frequency_rank:36,gender_note:"feminine",examples:[{armenian:"Mayrs usustuhi e",english:"My mother is a teacher",level:1}]},
  // TECHNOLOGY
  {id:"tech_001",word:"hagelust",english:["phone","telephone"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"technology",lesson_tags:["lesson_10"],frequency_rank:22,examples:[{armenian:"Im hagelustы lits e",english:"My phone is charged",level:1}]},
  {id:"tech_002",word:"hamakargich",english:["computer"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"technology",lesson_tags:["lesson_10"],frequency_rank:25,examples:[{armenian:"Hamakargchov em ashxatum",english:"I work with a computer",level:1}]},
  // BODY
  {id:"body_001",word:"glukh",english:["head"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:38,examples:[{armenian:"Glukhs kpor e",english:"My head hurts",level:1}]},
  {id:"body_002",word:"ach'k",english:["eye","eyes"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:29,examples:[{armenian:"Nora ach'kery karmir en",english:"His/her eyes are red",level:1}]},
  {id:"body_003",word:"dzerkh",english:["hand","arm"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:30,examples:[{armenian:"Lvay dzerkherd",english:"Wash your hands",level:1}]},
  {id:"body_004",word:"votk",english:["leg","foot"],synonyms:[],grammar_type:"noun",difficulty:1,embedding_group:"health_body",lesson_tags:["lesson_10"],frequency_rank:31,examples:[{armenian:"Votky kpor e",english:"The foot hurts",level:1}]},
];

export const SENTENCE_PATTERNS: SentencePattern[] = [
  {id:"sp_001",english_template:"I am going home",armenian_variants:["Ës gnum em tun","Ës tun em gnum","Tun em gnum","Gnum em tun"],grammar_note:"SOV/SVO both valid. Subject optional.",difficulty:1,lesson_tags:["lesson_2"],semantic_group:"motion_home"},
  {id:"sp_002",english_template:"I am eating bread",armenian_variants:["Ës hac em utum","Ës utum em hac","Hac em utum"],difficulty:1,lesson_tags:["lesson_3"],semantic_group:"eating_food"},
  {id:"sp_003",english_template:"I speak Armenian",armenian_variants:["Ës hayeren em xosum","Ës xosum em hayeren","Hayeren em xosum"],difficulty:1,lesson_tags:["lesson_2"],semantic_group:"language_communication"},
  {id:"sp_004",english_template:"I love Armenia",armenian_variants:["Ës sirum em Hayastany","Hayastany sirum em","Ës Hayastany sirum em"],difficulty:1,lesson_tags:["lesson_4"],semantic_group:"emotions_country"},
  {id:"sp_005",english_template:"I live in Yerevan",armenian_variants:["Ës Erevanum em aprum","Ës aprum em Erevanum","Erevanum em aprum"],difficulty:1,lesson_tags:["lesson_2"],semantic_group:"location_living"},
  {id:"sp_006",english_template:"My mother is a doctor",armenian_variants:["Mayrs bjshkuhi e","Mayrs bjishk e","Im mayry bjshkuhi e","Im mayry bjishk e","Mayrikms bjshkuhi e"],grammar_note:"Possessive suffix -s more natural. bjishk/bjshkuhi both accepted.",difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_professions"},
  {id:"sp_007",english_template:"My father is a teacher",armenian_variants:["Hayrs usucich e","Im hayry usucich e","Hayrikms usucich e","Hayrs usustuhi e"],grammar_note:"Possessive suffix -s preferred in natural speech",difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_professions"},
  {id:"sp_008",english_template:"I am reading a book",armenian_variants:["Ës gark em kardalum","Ës kardalum em gark","Gark em kardalum"],difficulty:1,lesson_tags:["lesson_5"],semantic_group:"education_reading"},
  {id:"sp_009",english_template:"How are you",armenian_variants:["Inch pes es?","Inch pes es du?","Vontsch es?","Inch e ka?"],grammar_note:"Vontsch es = colloquial. Inch pes es = standard.",difficulty:1,lesson_tags:["lesson_1"],semantic_group:"greetings"},
  {id:"sp_010",english_template:"I am fine",armenian_variants:["Lav em","Ës lav em","Shat lav em","Amen inch lav e"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"greetings_response"},
  {id:"sp_011",english_template:"Good morning",armenian_variants:["Bari loys","Bari arbanyan","Lav arbanyan"],grammar_note:"Bari loys = traditional. Bari arbanyan = standard.",difficulty:1,lesson_tags:["lesson_6"],semantic_group:"greetings_time"},
  {id:"sp_012",english_template:"Good night",armenian_variants:["Bari gisher","Anush gisher"],difficulty:1,lesson_tags:["lesson_6"],semantic_group:"greetings_time"},
  {id:"sp_013",english_template:"How much does it cost",armenian_variants:["Inch bajin e?","Inchkan arje?","Inch arje?"],difficulty:2,lesson_tags:["lesson_7"],semantic_group:"shopping"},
  {id:"sp_014",english_template:"My sister is a student",armenian_variants:["Quyrs usanox e","Im quyry usanox e","Quyrikms usanox e"],difficulty:1,lesson_tags:["lesson_4"],semantic_group:"family_education"},
  {id:"sp_015",english_template:"The sky is blue",armenian_variants:["Yerkinkы kapuyt e","Kapuyt e yerkinkы"],difficulty:1,lesson_tags:["lesson_8"],semantic_group:"nature_colors"},
  {id:"sp_016",english_template:"It is raining",armenian_variants:["Andzrev e galis","Andzrev e patel","Andzrev e"],difficulty:1,lesson_tags:["lesson_8"],semantic_group:"weather"},
  {id:"sp_017",english_template:"I am learning Armenian",armenian_variants:["Ës hayeren em soverum","Ës soverum em hayeren","Hayeren em soverum"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"language_learning"},
  {id:"sp_018",english_template:"Armenia is a beautiful country",armenian_variants:["Hayastany gshetsik yerkir e","Gshetsik yerkir e Hayastany","Hayastany shat gshetsik e"],difficulty:1,lesson_tags:["lesson_1"],semantic_group:"country_culture"},
  {id:"sp_019",english_template:"I drink coffee every morning",armenian_variants:["Amen arbanyan surj em xnum","Arbanyan surj em xnum","Ës amen or arbanyan surj em xnum"],difficulty:2,lesson_tags:["lesson_6"],semantic_group:"daily_routine_food"},
  {id:"sp_020",english_template:"I want water",armenian_variants:["Ës uzum em jur","Jur em uzum","Jur uzum em"],difficulty:1,lesson_tags:["lesson_3"],semantic_group:"food_desire"},
];

const LEXICON_MAP = new Map<string,LexiconEntry>(LEXICON.map(e=>[e.word,e]));
const ENGLISH_MAP = new Map<string,LexiconEntry[]>();
for(const e of LEXICON){for(const eng of e.english){const k=eng.toLowerCase();if(!ENGLISH_MAP.has(k))ENGLISH_MAP.set(k,[]);ENGLISH_MAP.get(k)!.push(e);}}
export const lookupArmenian=(w:string)=>LEXICON_MAP.get(w);
export const lookupEnglish=(w:string)=>ENGLISH_MAP.get(w.toLowerCase())??[];
export const lookupByCategory=(c:SemanticCategory)=>LEXICON.filter(e=>e.embedding_group===c);
export const lookupSentencePattern=(eng:string)=>SENTENCE_PATTERNS.find(p=>p.english_template.toLowerCase()===eng.toLowerCase());
export const getAllValidArmenianForms=(eng:string)=>lookupSentencePattern(eng)?.armenian_variants??[];
export const getSynonyms=(w:string)=>lookupArmenian(w)?.synonyms??[];
export const LEXICON_STATS={total:LEXICON.length,patterns:SENTENCE_PATTERNS.length,categories:[...new Set(LEXICON.map(e=>e.embedding_group))].length};
